[build]
publish="public"
functions="netlify/functions"
[[redirects]]
from="/api/create"
to="/.netlify/functions/create"
status=200
[[redirects]]
from="/api/image"
to="/.netlify/functions/image-background"
status=200
[[redirects]]
from="/api/image-edit"
to="/.netlify/functions/image-edit-background"
status=200
[[redirects]]
from="/api/image-status"
to="/.netlify/functions/image-status"
status=200
[[redirects]]
from="/api/news"
to="/.netlify/functions/news"
status=200
